/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./components/blog/Author.vue')['default']
    Avatar: typeof import('./components/base/Avatar.vue')['default']
    Blockquote: typeof import('./components/blog/Blockquote.vue')['default']
    Body: typeof import('./components/base/Body.vue')['default']
    Btn: typeof import('./components/base/Btn.vue')['default']
    Card: typeof import('./components/blog/Card.vue')['default']
    Divider: typeof import('./components/base/Divider.vue')['default']
    Feature: typeof import('./components/base/Feature.vue')['default']
    FeatureAlt: typeof import('./components/base/FeatureAlt.vue')['default']
    FeatureCard: typeof import('./components/base/FeatureCard.vue')['default']
    Heading: typeof import('./components/base/Heading.vue')['default']
    Post: typeof import('./components/blog/Post.vue')['default']
    PricingPlan: typeof import('./components/base/PricingPlan.vue')['default']
    Project: typeof import('./components/base/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/base/Section.vue')['default']
    SectionHeading: typeof import('./components/base/SectionHeading.vue')['default']
    SkillMeter: typeof import('./components/base/SkillMeter.vue')['default']
    Stat: typeof import('./components/base/Stat.vue')['default']
    Subheading: typeof import('./components/base/Subheading.vue')['default']
    Subtitle: typeof import('./components/base/Subtitle.vue')['default']
    Tag: typeof import('./components/base/Tag.vue')['default']
    TeamMember: typeof import('./components/base/TeamMember.vue')['default']
    Testimony: typeof import('./components/base/Testimony.vue')['default']
    Textarea: typeof import('./components/base/Textarea.vue')['default']
    TextField: typeof import('./components/base/TextField.vue')['default']
    Title: typeof import('./components/base/Title.vue')['default']
    Tweet: typeof import('./components/blog/Tweet.vue')['default']
  }
}
